### ISSUE TITLE
Separate dependencies from devDependencies

### ISSUE THREAD

**Issue by mauriciosoares** [weslleyaraujo/pokedux#10]
You should consider separating the dependencies in `package.json`, 

dependencies are every module that you need to run your project in production (ie.: react, isomorphic-fetch, redux).

devDependencies are every module that you need for development (ie.: webpack, babel).

![tumblr_inline_nb1du7661v1sen2mf](https://cloud.githubusercontent.com/assets/2321259/11790291/268b7310-a282-11e5-8a9a-546f517f44b4.jpg)

**Comment by weslleyaraujo** [comment]
I never thought I would be a sucker...
turns out that I am 😔

makes completely sense, will take look into that :+1:

**Comment by weslleyaraujo** [comment]
hey @mauriciosoares,

I kind of fixed this issue but I am not sure about some items such as `webpack` or `babel`...
well, I really don't know if those should be listed as devDependencies or an dependency itself..

what are your thoughts on it?

**Comment by mauriciosoares** [comment]
Probably devDependencies. 

Since webpack and babel are used in compilation time, the code generated by them will go to production, not the babel or webpack code itself.

I believe you should think like this, if you're requiring the module inside your personal code base (like `react` for example), than it's a dependency.

Otherwise it's a devDependency (like pre compilers and test tools).

**Comment by weslleyaraujo** [comment]
ah it makes sense...will follow that.
well I will just double check it again, I guess I still have some dependencies in the wrong place

thanks :)
